package com.goodpractices.demo.model.mapper;

import com.goodpractices.demo.data.entity.Example2Entity;
import com.goodpractices.demo.model.request.ExampleRequest;
import org.mapstruct.Mapper;

import static org.mapstruct.MappingConstants.ComponentModel.SPRING;
import static org.mapstruct.ReportingPolicy.IGNORE;

// This mapper has its attribute 'componentModel' set to SPRING
// But in this app we're not using it as a spring bean
// We use the method getMapper(...) in the MapperFactory class

// In case u want to use it as a spring bean u could use this interface wherever u want
// and the autogenerated implementation will be injected
@Mapper(componentModel = SPRING, unmappedTargetPolicy = IGNORE)
public interface ExampleRequestMapper {

    Example2Entity toEntity(ExampleRequest request);

}
